sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build --no-cache -t izonder/anny -f Dockerfile.test .

script:
  - docker run -it --rm izonder/anny cat /var/run/s6/services/docker-cmd/run
  - docker run -it --rm izonder/anny node -v -e 'true'

