sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build --no-cache -t izonder/anny -f Dockerfile.test .
  - docker build --no-cache -t izonder/anny-procps -f Dockerfile.procps .

script:
  - docker run --rm izonder/anny-procps ps xafo pid,ppid,pgid,sid,comm
  - docker run --rm izonder/anny echo 'test'
  - docker run --rm izonder/anny ps xafo pid,ppid,pgid,sid,comm
  - docker run --rm izonder/anny node -v -e 'true'

