sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build --no-cache -t izonder/anny -f Dockerfile.test .
  - docker build --no-cache -t izonder/anny-procps -f Dockerfile.procps .

script:
  - docker run -it --rm izonder/anny-procps ps auxf
  - docker run -it --rm izonder/anny ps auxf
  - docker run -it --rm izonder/anny node -v -e 'true'

