sudo: required

language: c

services:
  - docker

script:
  - docker info
  - docker build --no-cache -t izonder/anny -f Dockerfile.quick .
  - docker run -it --rm izonder/anny node -v
  - docker build --no-cache -t izonder/anny .
  - docker run -it --rm izonder/anny node -v

