FROM izonder/anny:latest

ADD https://jrjrtech.com/~john/s6-overlay-amd64.tar.gz /tmp/
RUN tar -zxf /tmp/s6-overlay-amd64.tar.gz -C /
RUN apk update && apk add procps strace
#COPY root /

ENTRYPOINT ["strace", "-f", "/init"]
