FROM alpine:3.6

ADD https://jrjrtech.com/~john/s6-overlay-amd64.tar.gz /tmp/
RUN tar -zxf /tmp/s6-overlay-amd64.tar.gz -C /
RUN apk update && apk add procps strace nginx

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./service/* /etc/services.d/*

ENTRYPOINT ["/init"]
